fix: split Models.java into individual files (Java requires one public class per file)
Java compiler requires each public class to be in a file matching its name.
Models.java contained 11 public classes (TaskStatus, StepType, Task,
JumpCondition, WorkflowStep, Workflow, SendMessageResult, TaskRequest,
TaskResponse, RouteDecision, ExecutionResult) which caused:
  error: Class 'TaskStatus' is public, should be declared in a file named 'TaskStatus.java'

Now each class has its own file:
  model/TaskStatus.java
  model/StepType.java
  model/Task.java
  model/JumpCondition.java
  model/WorkflowStep.java
  model/Workflow.java
  model/SendMessageResult.java
  model/TaskRequest.java
  model/TaskResponse.java
  model/RouteDecision.java
  model/ExecutionResult.java

Signed-off-by: Zhoujie628 <zhoujie628@gmail.com>
Signed-off-by: ZhouJie6 <ivo.zhou@huawei.com>
Signed-off-by: Zhoujie628 <zhoujie628@users.noreply.github.com>